name: ECS Build System

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame coverage

    - name: Run ECS Test Suite with Coverage
      run: |
        coverage run tests/run_tests.py

    - name: Generate Coverage Report
      run: |
        coverage report
        coverage html

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/

    - name: Build ECS Game Package
      run: |
        mkdir dist
        zip -r dist/bullet-hell-ecs.zip . -x '*.git*'

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: game-build
        path: dist/bullet-hell-ecs.zip 